print("===========================================")
print("          ÍNDICE DE MASA CORPORAL          ")
print("===========================================")
print("")
print("Ingrese su peso en kg: ")
peso = input()
print("")
print("Su peso es: " + peso + " kg")
print("")
print("Ingrese su altura en m: ")
altura = input()
print("")
print("Su altura es: " + altura + " m")
print("")
imc = round(float(peso)/float(altura)**2, 2)
print("Su índice de masa corporal es: ", imc)
print("===========================================")